### ISSUE TITLE
Cycling colors changes the value

### ISSUE THREAD

**Issue by jonwalstedt** [NTBBloodbath/color-converter.nvim#1]
When cycling the color format from hex > rgb > hsl > hex the value is no longer the same as the original hex value.

When starting with: #FFF4E7 i end up with #FFF4E5 after a full cycle, after yet another cycle i get #FFF2E0 and then #FFF0DB and so on.

I would expect it to return to the original value after a full cycle.

**Comment by NTBBloodbath** [comment]
Hey, thank you for reporting this!

It should be fixed now by commit [`3618e53`](https://github.com/NTBBloodbath/color-converter.nvim/commit/3618e535bd7a3243b6d1d6b164a5fbcf6fab4e47) (I'd a ton of changes and bug fixes on it), feel free to re-open this if you're still facing that issue.

Regards
