### ISSUE TITLE
to_hsl({ format = 'numeric' })

### ISSUE THREAD

**Issue by bennypowers** [NTBBloodbath/color-converter.nvim#3]
`to_hsl` should have some option to omit the `%` characters, for example, for editing lush templates

**Comment by bennypowers** [comment]
This'll do

```vim
nnoremap <leader>ch :lua require'color-converter'.to_hsl()<CR>:s/%//g<CR>
```

**Comment by jdrupal-dev** [comment]
@bennypowers Check out the updated version, now you have the possibility of configuring the HSL pattern.
